### ISSUE TITLE
Code Formatting Issue: Missing Space and Incorrect Indentation

### ISSUE THREAD

**Issue by Davichobits** [Davichobits/Auto-Type-Code#1]
When typing code, the formatting does not remain consistent. The expected formatting is altered, removing spaces and affecting indentation.

Steps to Reproduce:

```css
*{
   margin: 0;
   padding: 0;
   box-sizing: border-box;
}
```

And this is the result

```css
*{margin: 0;
padding: 0;
box-sizing: border-box;
}
```

## Expected Behavior:
- There should be a space between the opening bracket { and the first declaration.
- Proper indentation should be maintained.

## Actual Behavior:
- The space after { is removed.
- The indentation of the properties is not preserved correctly.
